### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by Martins3** [Martins3/loongson-dune#1]
## review mode
- [ ] how kvm_main works

## ideas
- [ ] host should work in another thread, then anything did in `host_loop` just like another thread, so it works just like two threads run in parallel.

**Comment by Martins3** [comment]
# TODO
- [ ] kvm_kick_many_cpus : how it works internally, it seems without any hardware support
- [ ] some function is static, `kvm_trap_vz_handle_tlb_st_miss` e.g., but I changed in dune, may lead to compiling problem

**Comment by Martins3** [comment]
Until I have no ideas, no todo and no question, can I compile the code.

**Comment by Martins3** [comment]
- [ ] 查看一下 access_ok 在 mips 上和 x86 上的不同。

**Comment by Martins3** [comment]
- [ ] use CMakelist
- [x] make these ioctl works
- [x] init
  - [x] create CPU

**Comment by Martins3** [comment]
- [x] /home/maritns3/core/tool/mips/kvm-cpu.c: kvm_cpu__set_debug_fd, so we can debug guset with debug_fd ?

**Comment by Martins3** [comment]
- [ ]  TLB init
- [ ] cache init
    - [ ] P079

**Comment by Martins3** [comment]
- [x] Loongson sdm : gpsi 11.3.1

**Comment by Martins3** [comment]
- [ ] host has to map PROT_EXEC ?
```c
// TODO why kvmtool ignored PROT_EXEC ?
#define PROT_RWX (PROT_READ | PROT_WRITE |PROT_EXEC)
#define MAP_ANON_NORESERVE (MAP_PRIVATE | MAP_ANONYMOUS | MAP_NORESERVE)

static inline void *alloc_ebase()
{
	void * addr = mmap(NULL, 1 << PAGESIZE, PROT_RWX, MAP_ANON_NORESERVE, -1, 0);
  if(addr == NULL)
    die_perror("alloc_ebase");

  return addr;
}

```

**Comment by Martins3** [comment]
- [x] TLB refill need page walk, in See MIPS Run, it's done by software, but with PW* registers, TLB refill can be done with hardware.

**Comment by Martins3** [comment]
- [ ] see 6.2.3 “Exception  Vector Locations” on page 103)

**Comment by Martins3** [comment]
```c
static inline unsigned int decode_config5(struct cpuinfo_mips *c)
```

**Comment by Martins3** [comment]
# We can do better
- [ ] why I can't run continue the program in the guest syscall handler
- [ ] guest and host share as minimal resources as possible
   - [ ] eg, guest can close any file descriptor?
- [ ] I hope I can run the unmodified binary
- [ ] We should share the same address space, so host and guest live in two threads
- [ ] can I let it run in python / rust / go ?

**Comment by Martins3** [comment]
- [ ] it's weird to ignore `cause` register on vcpu_put and vcpu_load
- [ ] check vcpu_load, what if two vm use same physical in turn ?
