### ISSUE TITLE
How to transport to Loongarch?

### ISSUE THREAD

**Issue by Martins3** [Martins3/loongson-dune#42]
Maybe we should set up a standard interface for developers to port to another system.

- [x] musl / gcc
  - [x] how clone works
- [x] ltp setup
- [x] kernel
  - [x] .config
  - [x] regs get and set method
- manual
  - [x] SIMD and float save and restore
  - [x] general register save and restore
  - [x] TLB refill entry 
  - [x] TLB refill
  - [x] CSR register setup
  - [x] Physical Address Range
  - [x] syscall entry
  - [x] xphysicall offset
  - [x] vmcall
- ABI
  - [x] callee saved and caller saved register
  - [x] gcc asm
    - [x] .set noat
    - [x] .set noreorder
  - [x] syscall
  - [x] why $2 is used for TLS register

**Comment by Martins3** [comment]
# TODO
- [ ] arch.h setup

**Comment by Martins3** [comment]
- [ ] vz manual check
  - [ ] CSR register
  - [ ] Hypercall

- [ ] SIMD

**Comment by Martins3** [comment]
- [ ] PIC / long jump
    - [ ] make a test ?

**Comment by Martins3** [comment]
- [ ] Please clean up all the notes before testing code

**Comment by Martins3** [comment]
```
[  441.895572] kvm [4153]: tlbrelo0: 0x120002000
[  441.895573] kvm [4153]: tlbrelo1: 0x00000000
[  441.899917] kvm [4153]: tlbrehi: 0x120002000
[  441.904158] kvm [4153]: tlbrehi: 0x120003485
[  441.908399] kvm [4153]: kvm_trap_vz_handle_hypcall internal error

 Registers:
 ----------
$0   : 0000000000000000 00000001200034c4 000000fff7833730 000000fffbc4f060
$4   : 0000000125684e10 000000fffbc4f1a8 0000000000000003 0000000000000001
$8   : 0000000000000006 0000000000000000 000000000000270f 00000000000000de
$12  : 000000fffbc4f1a8 000000fff7800000 0000000000000000 0000000125685390
$16  : 0000000000000004 0000000000000004 00000000000003ff 0000000000000000
$20  : 0000000000000000 0000000000000000 000000fffbc4f190 0000000000000000
$24  : 0000000120003968 000000fff6c69770 0000000000000000 000000fff6c69778
$28  : 000000fff6c697b8 00000001200d13d8 0000000000000000 00000001200d13d8
pc  : 0000000120003484
```

**Comment by Martins3** [comment]
- [x] re generate the compile_commans.json ?
